# Generated by Django 5.1.7 on 2025-07-26 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100000)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
